_wandb:
    value:
        cli_version: 0.23.1
        e:
            vzgkrge4qipecddbrsacz4rtzx9rh85t:
                args:
                    - train
                    - --batch_size=16
                    - --epochs=15
                    - --lr=0.0052438524755001135
                codePath: s4_debugging_profiling_logging\m14_logging\main_solution.py
                codePathLocal: main_solution.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510850494464"
                        used: "290516885504"
                email: alvarocuele@gmail.com
                executable: C:\Users\alvar\Desktop\02476_MLOPS\s4_debugging_profiling_logging\.venv\Scripts\python.exe
                git:
                    commit: 9ce435dcafcfa017f9e17ff1cddd8f0e5cd00f1c
                    remote: https://github.com/aql14/MLOps.git
                host: DESKTOP-7UGA8HT
                memory:
                    total: "16442789888"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\alvar\Desktop\02476_MLOPS\s4_debugging_profiling_logging\m14_logging\main_solution.py
                python: CPython 3.12.3
                root: C:\Users\alvar\Desktop\02476_MLOPS\s4_debugging_profiling_logging\m14_logging
                startedAt: "2026-01-13T17:14:10.378057Z"
                writerId: vzgkrge4qipecddbrsacz4rtzx9rh85t
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 16
                - 61
            "4": 3.12.3
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 15
lr:
    value: 0.0052438524755001135
